steps:
  - id: "Rodando docker-compose"
    name: 'docker/compose'
    args: ['-f','docker-compose.cloudbuild.yaml','up','-d']

  - id: "Chown in /var/www"
    name: 'docker'
    args: [ 'exec','-u','root','-t','micro-videos-app','chown','-R','www-data:www-data','/var/www' ]

  - id: "Rodando docker-compose ps"
    name: 'docker'
    args: ['ps']

  - id: "Rodando composer"
    name: 'docker'
    args: ['exec','-t','micro-videos-app','composer','install']

  - id: "Copiando .env"
    name: 'docker'
    args: ['exec','-t','micro-videos-app','cp','.env.exemple', '.env']
